import type { Metadata } from "next";
import { NavBar } from "@/components/shared/nav-bar";
import { Fragment } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
      <NavBar />
      {children}
    </Fragment>
  );
}
